name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract release notes from CHANGELOG
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          VERSION_NUMBER="${VERSION#v}"

          # Extract section for this version from CHANGELOG.md
          if grep -q "## \[${VERSION_NUMBER}\]" CHANGELOG.md; then
            awk "/## \[${VERSION_NUMBER}\]/,/^## \[/" CHANGELOG.md | sed '$d' | tail -n +2 > release_notes.md
          else
            echo "Release ${VERSION}" > release_notes.md
            echo "" >> release_notes.md
            echo "See [CHANGELOG.md](CHANGELOG.md) for details." >> release_notes.md
          fi

          # Add installation instructions
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo '```bash' >> release_notes.md
          echo "composer require agenziasmart/swotto" >> release_notes.md
          echo '```' >> release_notes.md
          echo "" >> release_notes.md
          echo "## Documentation" >> release_notes.md
          echo "" >> release_notes.md
          echo "- [README](https://github.com/agenziasmart/swotto#readme)" >> release_notes.md
          echo "- [CHANGELOG](https://github.com/agenziasmart/swotto/blob/master/CHANGELOG.md)" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify success
        run: |
          echo "✅ Release ${{ steps.version.outputs.VERSION }} created successfully!"
          echo "📦 Packagist will auto-update within a few minutes"
